development:
  admin-emails:
    - support@test.net

sandbox:
  admin-emails:
    - support@test.net

internal:
  admin-emails:
    - support@test.net

production:
  admin-emails:
    - support@test.net
